service: peba-run-ws
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  memorySize: 128
  stage: dev

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-iam-roles-per-function

functions:
  auth-user:
    handler: lambda/authorize.handle
    events:
      - httpApi:
          path: /auth-user
          method: post
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:GetItem"
        Resource:
          - !GetAtt AthleteTable.Arn

resources:
  Resources:
    AthleteTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: Athlete
