service: peba-run-ws
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  memorySize: 128
  stage: dev

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-iam-roles-per-function
  - serverless-plugin-monorepo
  - serverless-ssm-fetch
package:
  patterns:
  - 'node_modules/**'

functions:
  auth-user:
    handler: lambda/authorize.handle
    events:
      - httpApi:
          path: /auth-user
          method: post
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:GetItem"
        Resource:
          - !GetAtt AthleteTable.Arn

    ssmToEnvironment:
      - STRAVA_CLIENT_ID
      - STRAVA_CLIENT_SECRET

custom:
  serverlessSsmFetch:
    STRAVA_CLIENT_ID: /pebarun/dev/STRAVA_CLIENT_ID~true
    STRAVA_CLIENT_SECRET: /pebarun/dev/STRAVA_CLIENT_SECRET~true


resources:
  Resources:
    AthleteTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: Athlete
